-- ==========================================
-- SCRIPT MAESTRO DE CONFIGURACIÓN (V2)
-- ==========================================
-- Este script unifica TODOS los cambios necesarios para que el proyecto funcione.
-- Incluye:
-- 1. Tablas y Configuración de Envíos (Zonas y Moto)
-- 2. Nuevas columnas de Productos (Dimensiones, Packs, Mayorista)
-- 3. Tabla de Pedidos Personalizados
-- 4. Seguridad (Row Level Security)

-- ==========================================
-- 1. ZONAS DE ENVÍO (MOTO)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.shipping_zones (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL, 
    price numeric NOT NULL DEFAULT 0,
    free_threshold numeric, 
    zip_ranges jsonb DEFAULT '[]'::jsonb, 
    active boolean DEFAULT true
);

-- Insertar datos base SOLO si la tabla está vacía
INSERT INTO public.shipping_zones (name, price, zip_ranges, active)
SELECT 'CABA', 4500, '[{"min": 1000, "max": 1499}]'::jsonb, true
WHERE NOT EXISTS (SELECT 1 FROM public.shipping_zones LIMIT 1);

INSERT INTO public.shipping_zones (name, price, zip_ranges, active)
SELECT 'GBA Zona 1', 7500, '[{"min": 1500, "max": 1899}]'::jsonb, true
WHERE NOT EXISTS (SELECT 1 FROM public.shipping_zones WHERE name = 'GBA Zona 1');

INSERT INTO public.shipping_zones (name, price, zip_ranges, active)
SELECT 'GBA Zona 2', 9500, '[{"min": 1900, "max": 2999}]'::jsonb, true
WHERE NOT EXISTS (SELECT 1 FROM public.shipping_zones WHERE name = 'GBA Zona 2');


-- ==========================================
-- 2. ACTUALIZACIÓN DE PRODUCTOS
-- ==========================================

-- Dimensiones y Peso
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS dimensions jsonb DEFAULT '{"width": 10, "height": 10, "length": 10}';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS weight numeric DEFAULT 0;

-- Packs y Mayorista
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS pack_enabled boolean DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS pack_discount numeric DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS units_per_pack numeric DEFAULT 0;

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS mayorista_enabled boolean DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS wholesale_discount numeric DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS wholesale_min_units numeric DEFAULT 10;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS wholesale_units numeric DEFAULT 0; -- Alias
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS wholesale_image text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS wholesale_description text;


-- ==========================================
-- 3. PEDIDOS PERSONALIZADOS
-- ==========================================

CREATE TABLE IF NOT EXISTS custom_orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  description text not null,
  technology text, 
  status text default 'pendiente', 
  total_price numeric,
  deposit_amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- ==========================================
-- 4. SEGURIDAD (RLS)
-- ==========================================

-- Habilitar RLS en tablas clave
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_orders ENABLE ROW LEVEL SECURITY;

-- Limpiar políticas viejas para evitar duplicados (Clean Slate Strategy)
DROP POLICY IF EXISTS "Public products are viewable by everyone" ON products;
DROP POLICY IF EXISTS "Authenticated users can modify products" ON products;
DROP POLICY IF EXISTS "Public zones view" ON shipping_zones;
DROP POLICY IF EXISTS "Auth zones modify" ON shipping_zones;
DROP POLICY IF EXISTS "Admins can manage custom orders" ON custom_orders;

-- Crear Políticas Nuevas

-- PRODUCTOS: Todos ven, solo admin edita
CREATE POLICY "Public products are viewable by everyone" ON products FOR SELECT USING (true);
CREATE POLICY "Authenticated users can modify products" ON products FOR ALL USING (auth.role() = 'authenticated');

-- ZONAS DE ENVÍO: Todos ven, solo admin edita
CREATE POLICY "Public zones view" ON shipping_zones FOR SELECT USING (true);
CREATE POLICY "Auth zones modify" ON shipping_zones FOR ALL USING (auth.role() = 'authenticated');

-- PEDIDOS CUSTOM: Solo admin gestiona (el cliente ve info vía email por ahora, o local storage)
CREATE POLICY "Admins can manage custom orders" ON custom_orders FOR ALL USING (auth.role() = 'authenticated');

-- ==========================================
-- FINALIZADO
-- ==========================================
