-- Habilitar la extensión de almacenamiento si no está habilitada
-- (Storage suele venir habilitado por defecto, pero esto asegura las estructuras)

-- 1. Crear el bucket 'product-images' si no existe
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Eliminar políticas antiguas para evitar conflictos
DROP POLICY IF EXISTS "Public Access Select" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Insert" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Update" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Delete" ON storage.objects;

-- 3. Configurar políticas de seguridad (RLS) para 'product-images'
-- NOTA: Como el Admin usa un sistema de login propio y no Supabase Auth,
-- el usuario actúa como 'anon'. Para permitir la subida desde el Admin,
-- debemos permitir acceso al rol 'anon' o 'public'.
-- IMPORTANTE: Esto permite a cualquiera con la API Key pública subir archivos.
-- Para mayor seguridad, se debería migrar a Supabase Auth.

-- Permitir lectura pública a todos (para que se vean las fotos en la web)
CREATE POLICY "Public Access Select"
ON storage.objects FOR SELECT
USING ( bucket_id = 'product-images' );

-- Permitir subida (INSERT) a todos (rol anon incluido)
CREATE POLICY "Public Access Insert"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'product-images' );

-- Permitir actualización (UPDATE) a todos
CREATE POLICY "Public Access Update"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'product-images' );

-- Permitir borrado (DELETE) a todos
CREATE POLICY "Public Access Delete"
ON storage.objects FOR DELETE
USING ( bucket_id = 'product-images' );

-- 4. Verificar tabla de productos y asegurar columnas
-- Asegurarnos que la tabla 'products' tenga las columnas necesarias para las imágenes
CREATE TABLE IF NOT EXISTS public.products (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  price numeric NOT NULL DEFAULT 0,
  category text,
  image text,         -- URL de la imagen principal
  images jsonb,       -- Array de objetos {url, color}
  description text,
  technology text,
  featured boolean DEFAULT false,
  stock numeric,
  dimensions jsonb,   -- {width, height, length}
  weight numeric,
  created_at timestamptz DEFAULT now()
);

-- Habilitar RLS en products (opcional, si se quiere restringir)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Política permisiva para products (ya que usamos API anon desde admin custom)
DROP POLICY IF EXISTS "Enable all access for anon" ON public.products;
CREATE POLICY "Enable all access for anon"
ON public.products FOR ALL
USING (true)
WITH CHECK (true);
