-- 1. Enable RLS on Products
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Allow public read access (Store needs to see products)
CREATE POLICY "Public products are viewable by everyone" 
ON products FOR SELECT 
USING (true);

-- Allow insert/update/delete ONLY for authenticated users (Admins)
CREATE POLICY "Authenticated users can modify products" 
ON products FOR ALL 
USING (auth.role() = 'authenticated');

-- 2. Configure Shipping Zones Security
ALTER TABLE shipping_zones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public zones view" ON shipping_zones FOR SELECT USING (true);
CREATE POLICY "Auth zones modify" ON shipping_zones FOR ALL USING (auth.role() = 'authenticated');

-- 3. Custom Orders Table (For tracking custom jobs)
CREATE TABLE IF NOT EXISTS custom_orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  description text not null,
  technology text, -- '3D', 'Láser', 'Ambas'
  status text default 'pendiente', -- 'pendiente', 'cotizado', 'seña_pagada', 'en_progreso', 'completado'
  total_price numeric,
  deposit_amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Custom Orders
ALTER TABLE custom_orders ENABLE ROW LEVEL SECURITY;

-- Admins can do everything on custom orders
CREATE POLICY "Admins can manage custom orders" 
ON custom_orders FOR ALL 
USING (auth.role() = 'authenticated');

-- 4. Audit Log (Optional but good for security)
CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id),
  action text not null,
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins view logs" ON admin_audit_logs FOR SELECT USING (auth.role() = 'authenticated');
